### ISSUE TITLE
Idee

### ISSUE THREAD

**Issue by fazo96** [fazo96/asjon#1]
- [ ] internamento con diliberti
- [ ] interrogazioni
- [ ] orario scolastico
- [ ] compiti sul registro
- [ ] sistemare circolari
- [ ] meteo
- [ ] quanto manca agli esami
- [ ] elearning
- [ ] qualcosa per salvare memo per la classe
- [ ] impara e ricorda associazioni persona --> informazione ad esempio l'email di qualcuno

**Comment by ProFumino** [comment]
Richiesta l'implementazione di una risposta semplice ad un saluto
Esempio
"Ehi Asjon"
rispota
"Ehi dimmi!"

**Comment by MrSnork** [comment]
Implementazione saluto rivolto alla persona:
Leonardo:Ciao asjon
Asjon:Ciao Leonardo! ( con aggiunta una domanda o un'esclamazione)

**Comment by fazo96** [comment]
@MrSnork @ProFumino ho aggiunto la funzione che mi avete chiesto (era la stessa) potete vedere il cambiamento nel commit c2569b8bf4a6b308b68f30eff8af00335134d392

Chiudo questa issue perchè le cose da gestire sono diventate tante, quando volete proporre nuove idee apritene una nuova :+1: 

Sentitevi liberi di commentare e discutere riguardo ai bug o le varie funzioni!
