### ISSUE TITLE
integrazione con Wolfram Alpha

### ISSUE THREAD

**Issue by fazo96** [fazo96/asjon#10]
Collegarsi a wolfram e parsare i risultati della API call (XML)

Risorse:
- [Wolfram API Docs](http://products.wolframalpha.com/docs/WolframAlpha-API-Reference.pdf)
- cheerio per parsare XML?
- [questo plugin hubot](https://github.com/notpeter/hubot-wolfram/blob/master/src/wolfram.coffee)
- [questo package npm](https://www.npmjs.com/package/wolfram)

**Comment by asjonDalipaj** [comment]
Possibile soluzione: Prendere spunto da https://github.com/notpeter/hubot-wolfram

**Comment by fazo96** [comment]
grazie @asjonDalipaj, ho aggiornato la lista di risorse. Ci guarderò prossimamente, se no se qualcuno vuole provarci ben venga
