### ISSUE TITLE
riscrivere 'agenda' senza usare headless browser

### ISSUE THREAD

**Issue by fazo96** [fazo96/asjon#19]
Studiando bene come funziona mastercom dovrebbe essere possibile fare tutto solo tramite richieste http.

**Comment by rnhmjoj** [comment]
Chiedigli se ti danno un api.

**Comment by fazo96** [comment]
Non serve, ho parlato con nicola fossati (che ha sviluppato la famosa app android del galilei) e ha detto che si riesce a fare tutto solo con richieste http (senza js e quindi senza headless browser) però bisogna studiare bene il sito di mastercom. Non è disposto ad aiutarmi, però già il fatto che mi ha detto che è possibile (lui ha fatto così) mi basta

**Comment by fazo96** [comment]
Direi che questo è inutile adesso
