### ISSUE TITLE
abilità di generare memes

### ISSUE THREAD

**Issue by fazo96** [fazo96/asjon#24]
usando [memegen](https://github.com/jacebrowning/memegen) non dovrebbe essere per niente hard.

- [x] possibilità di creare memes al volo
- [x] avere la lista dei memes disponibili
- [x] ~~meme con custom immagine~~ impossibile (o quasi) da implementare
- [x] sintassi user friendly

**Comment by rnhmjoj** [comment]
La sintassi user friendly ora c'è.

**Comment by rnhmjoj** [comment]
6c3e6730e73a0081ac1983c64a39cdb7dda547fe aggiunge la list dei memes.

**Comment by rnhmjoj** [comment]
Per quanto riguarda i custom template memegen.link non permette di cambiare l'immagine del meme, forse con un'altra api. In ogni caso bisognerebbe usare un url perché è impossibile fare che asjon riceva un file e così non è tanto comodo.

**Comment by fazo96** [comment]
Hai ragione. Sistemo la issue
