### ISSUE TITLE
Easter eggs!

### ISSUE THREAD

**Issue by fazo96** [fazo96/asjon#7]
Proponete o discutete qui le funzioni inutili ma divertenti di Asjon.

Easter egg che verranno implementati: 

- [x] internamento con diliberti

**Comment by MrSnork** [comment]
Altri easter eggs stupidi:
-pony con lucca
-molise con migno
-indiano con singh
-prevendite con trogu
-praticamente con frittoli(dipende se avrai voglia di metterlo nel gruppo con friz)
-opla con dilda
altri boh

**Comment by fazo96** [comment]
ho visto che @ravinderpal ha implementato alcune proposte di @MrSnork. la prossima volta usate l'elenco con le crocette così potete crocettare quelli già fatti :+1:

**Comment by fazo96** [comment]
Direi che questo ha stufato
