### ISSUE TITLE
Argomenti

### ISSUE THREAD

**Issue by MrSnork** [fazo96/asjon#8]
Sarebbe molto utile conoscere in modo ordinato tutti gli argomenti dell'anno suddivisi per materia, prendendoli dal database della scuola o inserire manualmente quelli che mancano. Comunque ho in mente ad esempio:
Leo:Asjon cosa abbiamo fatto di storia?
Asjon:capitolo 1-ciccio bombo
          capitolo 2-terza guerra mondiale
          capitolo 3-isis strikes again 
eccetera eccetera

**Comment by fazo96** [comment]
bella idea, però è già possibile usando la funzione di memoria di asjon ('asjon ricordati che...') quindi non mi sembra che abbia senso implementare qualcosa di nuovo.

Prova a dirgli "asjon ricordati che gli argomenti di storia che abbiamo fatto sono ..."
Chiudo la issue come invalida
